FROM ubuntu:22.04

CMD [ "/bin/bash" ]
RUN useradd -ms /bin/bash user1 && useradd -ms /bin/bash user2 && useradd -ms /bin/bash user3
RUN mkdir -p /shared/rh && touch /shared/rh/texto.txt && echo adoro recursos humanos >> /shared/rh/texto.txt && mkdir -p /shared/contabilidade && touch /shared/contabilidade/texto.txt && echo adoro contabilidade >> /shared/contabilidade/texto.txt
RUN groupadd rh && groupadd contabilidade && usermod -aG rh user1 && usermod -aG rh user2 && usermod -aG contabilidade user3 && chown root:rh /shared/rh && chown root:contabilidade /shared/contabilidade && chmod 770 /shared/rh && chmod 770 /shared/contabilidade